name: Build and Deploy Web Api to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: github
        uses: actions/checkout@v4

      - name: Set up WebApi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: SHA from commit
        id: vars
        run:
          echo "short_sha=$(git rev-parse --short ~{{ githab.sha }})" >> "GITHUB_OUTPUT"

      - name: Build and push docker image to ACR
        env:
          ACR_REGISTRY: ${{ vars.ACR_SERVER }}
          IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
        run: 
          docker build -f MasterNet.Dockerfile \
           -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
           -t $ACR_REGISTRY/netapp:latest \
          .
          docker push $ACR_REGISTRY/netapp --all-tags

      # - name: Restore dependencies
      #   run: dotnet restore src/MasterNet.WebApi/MasterNet.WebApi.csproj
      # - name: Build the project
      #   run: dotnet build --configuration Release --no-restore YourApiProject/YourApiProject.csproj
      # - name: Publish the project
      #   run: dotnet publish --configuration Release --no-build --output ./publish YourApiProject/YourApiProject.csproj
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'YourAzureWebAppName'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ./publish  