name: Build and Deploy Web Api to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up WebApi .NET
        uses: actions/setup-dotnet@v4
        with:
          # Cambia esto a la versión real de tu proyecto (.NET 6, 7, 8…)
          dotnet-version: '8.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}    # ej: magodevopsdeveusacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push docker image to ACR
        env:
          ACR_REGISTRY: ${{ vars.ACR_SERVER }}    # magodevopsdeveusacr.azurecr.io
          IMAGE_TAG: ${{ github.sha }}           # usamos el SHA completo del commit
        run: |
          echo "Using IMAGE_TAG=$IMAGE_TAG"

          docker build -f Dockerfile \
            -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
            -t $ACR_REGISTRY/netapp:latest \
            .

          docker push $ACR_REGISTRY/netapp:$IMAGE_TAG
          docker push $ACR_REGISTRY/netapp:latest

  deploy-app-to-aca:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          # IMPORTANTE:
          # vars.ACR_SERVER debe ser algo como: magodevopsdeveusacr.azurecr.io
          # y el repo es "netapp", igual que en el build
          imageToDeploy: ${{ vars.ACR_SERVER }}/netapp:${{ github.sha }}
          registryUrl: ${{ vars.ACR_SERVER }}
          containerAppName: mago-devops-dev-eus-app
          containerAppEnvironment: mago-devops-dev-eus-acae
          resourceGroup: mago-devops-dev-eus-rg
          targetPort: 8080
          ingress: external
          environmentVariables: >
            ASPNETCORE_ENVIRONMENT=Development
            ASPNETCORE_URLS=http://+:8080
