name: Build and Deploy Web Api to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: github
        uses: actions/checkout@v4

      - name: Set up WebApi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # - name: Restore dependencies
      #   run: dotnet restore src/MasterNet.WebApi/MasterNet.WebApi.csproj
      # - name: Build the project
      #   run: dotnet build --configuration Release --no-restore YourApiProject/YourApiProject.csproj
      # - name: Publish the project
      #   run: dotnet publish --configuration Release --no-build --output ./publish YourApiProject/YourApiProject.csproj
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'YourAzureWebAppName'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ./publish  