name: Build and Deploy Web Api to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: github
        uses: actions/checkout@v4

      - name: Set up WebApi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: SHA from commit
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short {{ githab.sha }})" >> $GITHUB_OUTPUT

      - name: Build and push docker image to ACR
        env:
          ACR_REGISTRY: ${{ vars.ACR_SERVER }}
        run: |
          # Usamos los primeros 7 caracteres del commit como tag
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "Using IMAGE_TAG=$IMAGE_TAG"

          docker build -f Dockerfile \
            -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
            -t $ACR_REGISTRY/netapp:latest \
            .

          # Hacemos push explícito de ambas etiquetas
          docker push $ACR_REGISTRY/netapp:$IMAGE_TAG
          docker push $ACR_REGISTRY/netapp:latest

  deploy-app-to-aca:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Deploy to Azure Container Apps
      #   uses: azure/cli@v1
      #   with:
      #     inlineScript: |
      #       az containerapp update \
      #         --name ${{ vars.ACA_NAME }} \
      #         --resource-group ${{ vars.ACA_RESOURCE_GROUP }} \
      #         --image ${{ vars.ACR_SERVER }}/netapp:${{ needs.build-and-deploy.outputs.short_sha }} \
      #         --registry-server ${{ vars.ACR_SERVER }} \
      #         --registry-username ${{ secrets.ACR_USERNAME }} \
      #         --registry-password ${{ secrets.ACR_PASSWORD }}
